-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/Anmol/Desktop/UART_v2/UART/top_testbench_isim_beh.exe" -prj "C:/Users/Anmol/Desktop/UART_v2/UART/top_testbench_beh.prj" "work.top_testbench" 
